### ISSUE TITLE
[bug] "(X) command 'vscode-editor-group-minimizer.minimize' not found" until "Minimized Groups" in Explorer panel is unfolded

### ISSUE THREAD

**Issue by gamepad-coder** [suhay/vscode-editor-group-minimizer#1]
First off, awesome extension.

Using `Editor Group Minimizer` version `1.0.1`

### Bug Summary :
Bug where the `Editor Group Minimizer` extension is not registering its command  (and maybe not properly initializing) for use in Visual Studio Code on start. 

Attempts to use the extension result in VS Code error popups:
`command 'vscode-editor-group-minimizer.minimize' not found`.

This only happens when the "Minimized Groups" entry is folded in the Explorer panel on VS Code start (or when the extension is first installed).

Extension commands for Editor Group Minimizer become recognized & available once the "Minimized Groups" entry is unfolded one time in the Explorer Panel. 

From there: folding the Explorer Panel > "Minimized Groups" entry does not re-trigger error popups for `(X) command .. not found`. But no commands in this extension work in a newly opened VS Code instance (with the entry initially folded) until this Explorer entry is interacted with one time. 

And even then it seems to only send one tab to a "Minimized Group", instead of the entire set of tabs in the Workspace Group.

---

### Steps To Reproduce :

1. Ensure "Minimized Groups" entry is folded in the Explorer panel <img width="178" alt="2020-05-30 13_53_00-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83336930-ecc1f500-a27c-11ea-9d28-62006f0d0bcd.png">
2. Restart Visual Studio Code
3. Have some open tabs in a Workspace Group
4. Click Group's "..." button, click "Minimize Editor Group" <img width="516" alt="2020-05-30 14_17_03-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337351-47a91b80-a280-11ea-8462-6e9033cae73b.png">

### Expected :
- Groups to be minimized to a new entry in "Minimized Groups"

### Bug :
- VS Code error popup: 
  `(X) command 'vscode-editor-group-minimizer.minimize' not found`
  <img width="516" alt="2020-05-30 14_22_33-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337452-06fdd200-a281-11ea-8975-2c8dcf005b46.png">
---

### Setup :
- Open VS Code with Explorer Panel > "Minimized Groups" folded
  (see steps [1] and [2] above)
- Open VS Code's "Explorer" Panel if not already open

### Steps :
1. Observe entry for "Minimized Groups" 
  (at the bottom if no other extensions) <img width="516" alt="2020-05-30 14_38_56-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337741-74aafd80-a283-11ea-9369-ab56a4a20066.png">

2. Click this entry in the Explorer Panel once
  to un-fold the panel item for the "Editor Group Minimizer" extension <img width="516" alt="2020-05-30 14_38_58-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337743-75439400-a283-11ea-9ff8-2a92f3beab5f.png">
3. Try to minimize a Workspace Group again <img width="516" alt="2020-05-30 14_39_01-1 test html - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337744-75dc2a80-a283-11ea-9310-c89f0927dccb.png">
4.  Outcome: command found!
    ...but only one tab added to group <img width="516" alt="2020-05-30 14_39_06-3 test txt - Visual Studio Code" src="https://user-images.githubusercontent.com/65138515/83337745-75dc2a80-a283-11ea-83ea-bb00ae317401.png">

<hr>

Love this extension.

Couldn't figure out why it wouldn't work at first.

Hope this helps.

**Comment by suhay** [comment]
Good catch! And props for the amazing repro steps!
