### ISSUE TITLE
Not saving all tabs

### ISSUE THREAD

**Issue by msantoro12** [suhay/vscode-editor-group-minimizer#3]
Right now when I try to minimize the tabs its only putting in the selected tab or a few of them randomly :(. I love this extension

**Comment by suhay** [comment]
Yeah, I've been noticing that too while using it. I'll dig into it and see if there is a more dependable way to collect all the open editors without needing them to ever be marked as `active`. What's happening is if a tab is opened, but never selected before being minimized, it gets skipped.

Thanks for filing the bug! More soon...
