### ISSUE TITLE
REQ: rename minimized groups

### ISSUE THREAD

**Issue by vince-roll20** [suhay/vscode-editor-group-minimizer#5]
Love this extension.   I often have to expand my various groups to peek at what they actually are.  Would it be possible to allow the minimized groups to be renamed?  I think this would be a great addition.  Cheers

**Comment by suhay** [comment]
Yeah that's a great idea!

**Comment by vince-roll20** [comment]
Sweet.

**Comment by vince-roll20** [comment]
Works like a charm.  Thanks for adding this feature!
