### ISSUE TITLE
Minimize for one window combines all windows into one group

### ISSUE THREAD

**Issue by bedge** [suhay/vscode-editor-group-minimizer#9]
3 windows open, with ~5 files per window
3 vertical panes
Chose "minimize group" in central window
Closes all files and creates a single minimized group
Reopening the minimized group reopens all files in a single window.

No way back to original layout.

**Comment by suhay** [comment]
Sorry for the delay! Let me see what I can do.

**Comment by suhay** [comment]
It looks like the way VSCode handles which panes hold which editors is being a bit difficult to track down. I might be missing something or it might be impossible with the current exposed API. I'll keep playing around with it and seeing what I can do, but this might not be possible for right now.
